### ISSUE TITLE
Add GW-FEAST section to website

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/hivelab#52]
Please add a GW-FEAST section to the _Projects_ page of the lab website and link it to https://hivelab.biochemistry.gwu.edu/gw-feast. I will add content to this blurb in the next day or so.

**Blurb**
The GW Federated Ecosystems for Analytics and Standardized Technologies (GW-FEAST) project is part of the ARPA-H FEAST performer team initiative that includes academic and industry partners. The goal of the ARPA-H performer teams is “to create bridges across data silos to make health data more accessible and usable”.

**Comment by BVishal-Work** [comment]
@lorikrammer Do we have any images to be displayed ?
